name: Ion Java automatically release to Maven Central

on: 
  push:
    branches: [ test ]

jobs:
  ion-java-auto-release:
    name: ion-java-auto-release

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - uses: actions/checkout@v3
        with:
         repository: amzn/ion-java
         
      - name: Check the previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          exclude_types: "release"
          view_top: 1
          path: last_release
          
      - name: Git commit ID of these two versions
        run: |
         echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"

    
