name: Ion Java automatically release to Maven Central

on: 
  push:
    branches: [ test ]

jobs:
  ion-java-auto-release:
    name: ion-java-auto-release

    runs-on: ubuntu-latest

    steps:
      - name: Check the previous release
        uses: oprypin/find-latest-tag@v1
        id: check_last_release 
        with:
          repository: amzn/ion-java
          releases-only: true 

      - name: Checkout the current commit id
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          path: current_release
          
      - name: Get the commit id of the current release
        run: |
         cd current_release
         echo "current_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV
         if git merge-base --is-ancestor a90e7ca b885cbc; then echo "yes"; else echo "no";fi

      - name: Checkout the last relase's commit id
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          ref: ${{ steps.check_last_release.outputs.tag }}
          path: last_release
              
      - name: Get the commit id of the last release
        run: |
         cd last_release
         echo "last_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV
         

         

