name: Ion Java automatically release to Maven Central

on: 
  push:
    branches: [ test ]

jobs:
  ion-java-auto-release:
    name: ion-java-auto-release

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Check the previous release
        uses: oprypin/find-latest-tag@v1
        id: checkrelease 
        with:
          repository: amzn/ion-java
          releases-only: true 

      - name: Git commit ID of these two versions
        run: |
         echo "Octokit is at version ${{ steps.checkrelease.outputs.tag }}"

    
