name: Fast-forward checking before release
on: [pull_request]


jobs:
  check-version-changes:
    name: check-version-changes
    runs-on: ubuntu-latest
    steps:
      - name: Switch to the branch of in-coming pull request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ion-java-new

      - name: Check if the in-coming commit contains version number changes
        run: |
          cd ion-java-new
          commitID=$(git rev-parse HEAD)
          echo $commitID
          readmeChange=$(git show $commitID -- ./README.md)
          pomChange=$(git show $commitID -- ./pom.xml)
          echo $readmeChange
          echo $pomChange
          if [[ $readmeChange != "" && $readmeChange =~ ."<versions>"."</version>".* ]] && [[ $pomChange != "" && $pomChange =~ ."<versions>"."</version>".* ]]; then echo "version bump check pass"; else exit 1; fi 


  ion-java-gitHub-auto-release:
    name: ion-java-github-auto-release
    runs-on: ubuntu-latest

    steps:
      - name: Access to the last release
        uses: oprypin/find-latest-tag@v1
        id: check_last_release
        with:
          repository: amzn/ion-java
          releases-only: true

      - name: Checkout the last release
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          ref: ${{ steps.check_last_release.outputs.tag }}
          path: last_release

      - name: Get the commit id of the last release
        run: |
          cd last_release
          echo "last_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Access to the incoming release
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java

      - name: Checkout PR
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.number }}


      - name: Get the commit id of the incoming release
        run: |
          echo "current_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo $(git rev-parse HEAD)

      - name: Check whether the incoming release is fast-forward compared to the last release
        run: |
          cd current_release 
          if git merge-base --is-ancestor ${{env.last_release_commit_id}} ${{env.current_release_commit_id}}; then echo "Trigger github release"; else exit 1; fi 
