name: Create Release after fast-forward check
on: 
  push:
    branches: [ test ]

jobs:

  ion-java-gitHub-auto-release:
    name: ion-java-github-auto-release
    runs-on: ubuntu-latest

    steps:
      - name: Access to the incoming release
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          path: current_release
          
      - name: Build ion-java
        run: |
          cd current_release
          git submodule init
          git submodule update
          mvn clean install
          
      - name: Upload the executable jar to artifacts
        run: |
          cd current_release/target
          echo "path=$(readlink -f $(ls *.jar))" >> $GITHUB_ENV
      
      - name: Upload the executable jar to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: asset.jar
          path: ${{ env.path }}
          
      - name: Create new release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.9.6SNAPSHOT
          release_name: ion-java-test-release
          
          
          
     
