name: Create Release after fast-forward check
on: 
  push:
    branches: [ test ]

jobs:

  ion-java-gitHub-auto-release:
    name: ion-java-github-auto-release
    runs-on: ubuntu-latest

    steps:
      - name: Access to the incoming release
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          path: current_release
          
      - name: Build ion-java
        run: |
          cd current_release
          git submodule init
          git submodule update
          mvn clean install
          
      - name: Upload the executable jar to artifacts
        run: |
          cd current_release/target
          echo "path=$(readlink -f $(ls *.jar))" >> $GITHUB_ENV
      
      - name: Upload the executable jar to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: asset.jar
          path: ${{ env.path }}
          
      - name: Create new release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v1.9.7SNAPSHOT
          release_name: ion-java-test-release-01
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: asset.jar
          
      - run: ls
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./asset.jar
          asset_name: asset.jar
          asset_content_type: application/zip

          
          
          
     
