name: Create Release after fast-forward check
on: [pull_request]

jobs:
  check-version-change:
    name: check-version-change
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repository master branch
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java
          ref: master
          fetch-depth: 2
          path: ion-java-current

      - name: Check whether the pull request contains version number bump
        id: check-version-change
        run: |
          cd ion-java-current
          versionNew=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $versionNew
          git reset --hard HEAD^          
          versionCurrent=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $versionCurrent
          if [[ $versionNew != $versionCurrent ]]; then echo "version check pass"; else exit 1; fi

  ion-java-gitHub-auto-release:
    needs: check-version-change
    if: ${{ success() }}
    name: ion-java-github-auto-release
    runs-on: ubuntu-latest

    steps:
      - name: Access to the incoming release
        uses: actions/checkout@v3
        with:
          repository: amzn/ion-java
          path: current_release

      - name: Build ion-java
        run: |
          cd current_release
          mvn clean install -DskipTests

      - name: Upload the executable jar to artifacts
        run: |
          cd current_release/target
          echo "path=$(readlink -f $(ls *.jar))" >> $GITHUB_ENV
          echo "file_name=$(ls *.jar)" >> $GITHUB_ENV
          echo "version_number=$(echo $(ls *.jar) | cut -d'-' -f3)" >> $GITHUB_ENV





