# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Ion Jave performance regression detector

on:
  push:
    branches: [ master ]

jobs:
  build-ion-java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2



        with:
          fetch-depth: 2
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git checkout HEAD^
      - run: mvn clean install



      - uses: actions/checkout@v2
        with:
          repository: amzn/ion-java-benchmark-cli
          ref: master

      - name: Build with Maven
        run: mvn clean install
      - name: Verify the CLI executes
        run: java -jar target/ion-java-benchmark-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar --version
      - name: clean maven repository
        run : rm -r /home/runner/.m2

      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install

      - uses: actions/checkout@v2
        with:
          repository: amzn/ion-java-benchmark-cli
          ref: master

      - name: Build with Maven
        run: mvn clean install
      - name: Verify the CLI executes
        run: java -jar target/ion-java-benchmark-cli-0.0.1-SNAPSHOT-jar-with-dependencies.jar --version