name: Ion Java performance regression detector

on: [pull_request]

jobs:
  detect-regression:
    name: Detect Regression

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout ion-java from the new commit.
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: recursive
          path: ion-java
          
      - run: cd ion-java && git log
