name: Version-bump-and-fast-forward-check
on: [pull_request]

jobs:
  check-version-bump:
    uses: linlin-s/ion-java/.github/workflows/version-number-check.yml@testVersionChange

  fast-forward-check:
    needs: check-version-bump
    name: fast-forward-check
    if: ${{ steps.check-version-bump.outputs.result == "pass" }}
    runs-on: ubuntu-latest
    steps:
      - name: Access to the last release
        uses: oprypin/find-latest-tag@v1
        id: check_last_release
        with:
          repository: linlin-s/ion-java
          releases-only: true

      - name: Checkout the last release
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java
          ref: ${{ steps.check_last_release.outputs.tag }}
          path: last-release

      - name: Get the commit id of the last release
        run: |
          cd last-release
          echo "last_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Access to the incoming release
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java
          ref: ${{ github.event.pull_request.head.sha }}
          path: ion-java-new

      - name: Get the commit id of the incoming release
        run: |
          cd ion-java-new
          echo "current_release_commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo $(git rev-parse HEAD)

      - name: Check whether the incoming release is fast-forward compared to the last release
        run: |
          cd ion-java-new 
          if git merge-base --is-ancestor ${{env.current_release_commit_id}} ${{env.current_release_commit_id}}; then echo "Trigger github release"; else exit 1; fi 

      - name: comment
        if: steps.build.outputs.exit_code == 0
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This PR passes version bump check and fast-forward check, please double check the version number and merge this PR. After merging this PR, please trigger "Create gitHub prerelease after fast-forward check" workflow manually to create prerelease.

      - name: comment
        if: steps.build.outputs.exit_code == 1
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This PR is not fast-forward compared to the last release, please check.
