name: Version-bump-check

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  check-version-bump:
    name: check-version-bump
    runs-on: ubuntu-latest
    steps:
      - name: Switch to the branch of the pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ion-java-new

      - name: Checkout the current repository master branch
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java
          ref: master
          path: ion-java-current

      - name: Check whether the pull request contains version number bump
        run: |
          cd /home/runner/work/ion-java/ion-java/ion-java-new
          versionNew=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          commitID=$(git rev-parse HEAD)
          cd /home/runner/work/ion-java/ion-java/ion-java-current
          versionCurrent=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $versionNew != $versionCurrent ]]; then echo "version bump check pass"; else exit 1; fi 
