name: Version-bump-check

on:
  workflow_call:

jobs:
  check-version-bump:
    name: check-version-bump
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.version-check.outputs.result }}
    steps:
      - name: Switch to the branch of the pull request
        id: version-check
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ion-java-new

      - name: Checkout the current repository master branch
        uses: actions/checkout@v3
        with:
          repository: linlin-s/ion-java
          ref: master
          path: ion-java-current

      - name: Check whether the pull request contains version number bump
        run: |
          cd /home/runner/work/ion-java/ion-java/ion-java-new
          versionNew=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          commitID=$(git rev-parse HEAD)
          cd /home/runner/work/ion-java/ion-java/ion-java-current
          versionCurrent=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $versionNew != $versionCurrent ]]; then echo "::set-output name=result::pass"; else echo "::set-output name=result::failed"; fi 
